name: chatgpt

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

include: package:flutter_lints/flutter.yaml